Added render class for Viewfield.
wellebee/viewfield pull request #4
Opened 2016-08-05 01:39 UTC by marcus-n3rd

Absorbed the following functions into the class:
- viewfield_element_info()
- viewfield_pre_render()
- viewfield_post_render()
- _viewfield_get_view_args()
-- This was made getViewArgs() which is a protected method

Left rendering for the theme, i.e.: removed `$output = render ($view_el);`, other than that I didn't touch any logic within the functions. 

Thank Metal Toad for paying my hours for this. Lightly tested this on a client's project and I'd say it's now eligible to go from sandbox to full project status.

2016-09-20 17:46 UTC, marcus-n3rd commented
I combined the changes from:
- @seanbeaton 's https://github.com/derhasi/viewfield/pull/5
- @luksak 's https://github.com/derhasi/viewfield/pull/2

2016-09-30 12:16 UTC, derhasi requested changes
@marcus-n3rd, thanks for your work. I'm just starting getting into the issues again after some months.

Here are some issues I found from a "meta" perspective. I will have a closer look at the functionality itself later.

2016-09-30 12:16 UTC, derhasi commented on src/Render/Element/Viewfield.php
> +namespace Drupal\Core\Render\Element;
It should not use core's namespace, but `Drupal\viewfield\...` instead.

2016-09-30 12:16 UTC, derhasi commented on src/Render/Element/Viewfield.php
> +  public function getInfo() {
This needs at least function documentation. I guess `{@inheritdoc}` should do its job here.

2016-09-30 12:16 UTC, derhasi commented on src/Render/Element/Viewfield.php
> +  public static function preRenderViewfield($element) {
This needs some proper function documentation and type declaration.

2016-09-30 12:16 UTC, derhasi commented on src/Render/Element/Viewfield.php
> +  public static function postRenderViewfield($content, $element) {
This needs some proper function documentation and type declaration too.

2016-09-30 12:16 UTC, derhasi commented on src/Render/Element/Viewfield.php
> +  protected function getViewArgs($vargs, $entity_type, $entity) {
There needs to be some parameter documentation.

2016-10-03 23:30 UTC, marcus-n3rd commented
Oh fudge. While step debugging through in order to double check the argument types, I found that none of Viewfield class is actually used. :facepalm: I'm going to run through and see if there are parts that can be consumed and used in the other classes.

2016-10-04 00:46 UTC, marcus-n3rd commented
I am really pondering the value of having it as a RenderElement. Could the functionality just be moved into the ViewfieldDefaultFormatter (with the theme name changing to simply `viewfield` rather than `viewfield_formatter_default`)? Is the `viewfield_stack` static variable still needed with Drupal 8's render caching, because that would get rid of the need of the pre/post rendering functions/methods?

2016-10-14 09:48 UTC, luksak commented
Well, I was trying to fix the caching issues and added that in the field formatter. As Berdir suggested, we should move that somewhere else where the render array is being built and that is what you approach does, right?

2016-10-24 23:16 UTC, marcus-n3rd commented
Closing in preference of #8.

2016-10-24 23:16 UTC, closed without merging